package components

import (
	"github.com/infra-rdc/rudder-go/internal/utils"
)

type GroupCategory struct {
	// The parent category of the groups
	Parent string `json:"parent"`
	// Group category id, only provide it when needed.
	ID *string `default:"{autogenerated}" json:"id"`
	// Name of the group category
	Name string `json:"name"`
	// Group category description
	Description *string `json:"description,omitempty"`
}

func (g GroupCategory) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GroupCategory) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GroupCategory) GetParent() string {
	if o == nil {
		return ""
	}
	return o.Parent
}

func (o *GroupCategory) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GroupCategory) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GroupCategory) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
