package components

import (
	"github.com/infra-rdc/rudder-go/internal/utils"
)

type RuleCategory struct {
	// The parent category of the rules
	Parent string `json:"parent"`
	// Rule category id, only provide it when needed.
	ID *string `default:"{autogenerated}" json:"id"`
	// Name of the rule category
	Name string `json:"name"`
	// Rules category description
	Description *string `json:"description,omitempty"`
}

func (r RuleCategory) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RuleCategory) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RuleCategory) GetParent() string {
	if o == nil {
		return ""
	}
	return o.Parent
}

func (o *RuleCategory) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *RuleCategory) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RuleCategory) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}
